# Generated by Django 6.1.1 on 2026-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Seeker', 'Seeker'), ('Recruiter', 'Recruiter')], default='Seeker', max_length=15),
        ),
    ]
